Algoritmo "exercicio 2"
// Disciplina   : UC9
// Professor   : Ingrid Batista 
// Descrição   : Reescreva a seguinte expressão
//              {2 x 5 - [7 - (3 - 1)] ÷ 2} de forma linear.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/11/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("{2 x 5 - [7 - (3 - 1)] ÷ 2}")
escreval((2 * 5 - (7 - (3 - 1)) / 2))

Fimalgoritmo