Algoritmo "exercicio 3"
// Disciplina   : UC9
// Professor   : Ingrid Batista 
// Descrição   : Reescreva a seguinte expressão {2 + [(v¯16  + 2³)]} x 3 de forma linear.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/11/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("{2 + [(v¯16  + 2³)]} x 3")
escreval((2 + ((raizq(16) + 2^3))) * 3)

Fimalgoritmo